package com.dino.backend.integration.gemini;

/**
 * Interface for Gemini 2.0 Flash API interactions.
 */
public interface GeminiAPI {
    /**
     * Generates a response from the Gemini API based on the provided input.
     *
     * @param input The input string to process.
     * @return A response string generated by the API.
     */
    String getResponse(String input);

    /**
     * Provides grammar feedback for the given input.
     *
     * @param input The input string to analyze.
     * @return A string with grammar feedback.
     */
    String getGrammarFeedback(String input);
}
